-- AlterTable
ALTER TABLE `pembayaran` MODIFY `metodePembayaran` ENUM('VIRTUAL_ACCOUNT', 'TUNAI', 'CARD', 'OVER_THE_COUNTER', 'DIRECT_DEBIT', 'BANK_TRANSFER', 'EWALLET', 'RETAIL_OUTLET', 'CREDIT_CARD', 'QR_CODE') NULL;
