const ROLE = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN_SURAU: 'ADMIN_SURAU',
  ADMIN: 'ADMIN',
  SISWA: 'SISWA',
  GURU: 'GURU'
};

const GENDER = {
  LAKI_LAKI: 'LAKI_LAKI',
  PEREMPUAN: 'PEREMPUAN',
};

const STRATA_PENDIDIKAN = {
  PAUD: 'PAUD',
  TK: 'TK',
  SD: 'SD',
  SMP: 'SMP',
  SMA: 'SMA',
  KULIAH: 'KULIAH',
  UMUM: 'UMUM'
};

const NAMA_KELAS = {
  MAKKAH: 'Makkah',
  MADINAH: 'Madinah',
  ALAQSA: 'Alaqsa',
  PUSTAKA: 'Pustaka',
  NABAWI: 'Nabawiy',
  SHAFA: 'Shafa',
  MARWAH: 'Marwah',
  PRIVATE: 'Private',

};

const PROGRAM = {
  PRE_BTA: 'Pre BTA',
  BTA_LVL_1: 'BTA LVL 1',
  BTA_LVL_2: 'BTA LVL 2',
  TAHSIN: 'Tahsin',
  TAHFIDZ: 'Tahfidz',
  PRIVATE: 'Private'
};

const TIPE_KELAS = {
  GROUP: 'Grup',
  PRIVATE: 'Private'
};

const HARI = {
  SENIN: 'SENIN',
  SELASA: 'SELASA',
  RABU: 'RABU',
  KAMIS: 'KAMIS',
  JUMAT: 'JUMAT',
  SABTU: 'SABTU'
};

const STATUS_PEMBAYARAN = {
  PENDING: 'PENDING',
  MENUNGGU_PEMBAYARAN: 'MENUNGGU_PEMBAYARAN',
  LUNAS: 'LUNAS',
  BELUM_BAYAR: 'BELUM_BAYAR',
  KADALUARSA: 'KADALUARSA',
  DIBATALKAN: 'DIBATALKAN'
};

const STATUS_VERIFIKASI = {
  MENUNGGU: 'MENUNGGU',
  DIVERIFIKASI: 'DIVERIFIKASI'
};

const STATUS_KEHADIRAN = {
  HADIR: 'HADIR',
  TIDAK_HADIR: 'TIDAK_HADIR',
  IZIN: 'IZIN',
  SAKIT: 'SAKIT'
};

const STATUS_SISWA = {
  AKTIF: 'AKTIF',
  TIDAK_AKTIF: 'TIDAK_AKTIF',
  CUTI: 'CUTI'
};

const STATUS_PAYROLL = {
  DRAFT: 'DRAFT',
  DIPROSES: 'DIPROSES',
  SELESAI: 'SELESAI',
  GAGAL: 'GAGAL'
};

const METODE_PEMBAYARAN = {
  TUNAI: 'TUNAI',
  VIRTUAL_ACCOUNT: 'VIRTUAL_ACCOUNT',
  EWALLET: 'EWALLET',
  RETAIL_OUTLET: 'RETAIL_OUTLET',
  CREDIT_CARD: 'CREDIT_CARD',
  QRIS: 'QRIS'
};

const TIPE_PEMBAYARAN = {
  PENDAFTARAN: 'PENDAFTARAN',
  SPP: 'SPP'
};

const TIPE_VOUCHER = {
  PERSENTASE: 'PERSENTASE',
  NOMINAL: 'NOMINAL'
};

const XENDIT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  SETTLED: 'SETTLED',
  EXPIRED: 'EXPIRED',
  FAILED: 'FAILED'
};

const XENDIT_DISBURSEMENT_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

module.exports = {
  ROLE,
  GENDER,
  STRATA_PENDIDIKAN,
  NAMA_KELAS,
  PROGRAM,
  TIPE_KELAS,
  HARI,
  STATUS_PEMBAYARAN,
  STATUS_VERIFIKASI,
  STATUS_KEHADIRAN,
  STATUS_SISWA,
  STATUS_PAYROLL,
  METODE_PEMBAYARAN,
  TIPE_PEMBAYARAN,
  TIPE_VOUCHER,
  XENDIT_STATUS,
  XENDIT_DISBURSEMENT_STATUS
};