name: Deploy Express API with Prisma to cPanel

on:
  push:
    branches: [main]  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Generate Prisma
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Compress project files
        run: |
          # Exclude files/directories yang tidak perlu di-deploy
          echo "node_modules/" > .deployignore
          echo ".git/" >> .deployignore
          echo ".github/" >> .deployignore
          echo ".env" >> .deployignore
          echo ".gitignore" >> .deployignore
          
          # Create tar archive dengan exclude list
          tar --exclude-from=.deployignore -czf deploy.tar.gz .
      
      - name: Deploy files to cPanel
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "deploy.tar.gz"
          target: "/home/metrosof/api/surau-quran-staging-api"
            

      - name: Setup application in cPanel
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /home/metrosof/api/surau-quran-staging-api
            
            # Backup .env jika sudah ada
            if [ -f .env ]; then
              cp .env .env.backup
            fi
            
            # Extract files
            tar -xzf deploy.tar.gz
            
            # Restore .env dari backup
            if [ -f .env.backup ]; then
              cp .env.backup .env
            else
              # Buat .env baru jika tidak ada backup
              echo "DATABASE_URL='${{ secrets.DATABASE_URL }}'" > .env
            fi
            
            # Install dependencies
            npm ci --only=production
            
            # Generate Prisma client di server
            npx prisma generate
            
            # Tentukan file entry point (index.js, app.js, atau server.js)
            ENTRY_POINT="index.js"
            if [ ! -f "$ENTRY_POINT" ]; then
              if [ -f "app.js" ]; then
                ENTRY_POINT="app.js"
              elif [ -f "server.js" ]; then
                ENTRY_POINT="server.js"
              fi
            fi
            
            echo "Using entry point: $ENTRY_POINT"
            
            # Restart atau mulai aplikasi dengan PM2
            if pm2 list | grep -q "surau-quran-api"; then
              pm2 restart surau-quran-api
            else
              pm2 start $ENTRY_POINT --name surau-quran-api
            fi
            
            # Bersihkan file tar
            rm deploy.tar.gz