name: Deploy Express API with Prisma to cPanel

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Generate Prisma
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

        
      - name: Deploy to cPanel via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # Menentukan path deploy
            DEPLOY_PATH="/home/metrosof/api/surau-quran-staging-api"
            mkdir -p $DEPLOY_PATH
            cd $DEPLOY_PATH
            
            # Dapatkan artifact terbaru (cara alternatif tanpa menggunakan tar langsung)
            # Bersihkan file lama jika perlu, tapi simpan node_modules dan .env
            find . -type f -not -path "./node_modules/*" -not -name ".env" -delete
            
            # Jika ingin menjaga node_modules tetap utuh
            #find . -type f -not -path "./node_modules/*" -not -name ".env" -delete
            
      - name: Compress build directory
        run: |
          tar -czf build.tar.gz  package.json package-lock.json ecosystem.config.js prisma/
          
      - name: Deploy files to cPanel
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }} 
          source: "build.tar.gz"
          target: "/home/metrosof/api/surau-quran-staging-api"
          
      - name: Setup application in cPanel
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }} 
          script: |
            cd /home/metrosof/api/surau-quran-staging-api
            tar -xzf build.tar.gz
            npm ci --only=production
            echo "DATABASE_URL='${{ secrets.DATABASE_URL }}'" > .env
            npx prisma generate
            if [ -f ~/.pm2/pm2.pid ]; then 
              pm2 restart surau-quran-api || pm2 start index.js --name surau-quran-api
            else 
              pm2 start index.js --name surau-quran-api
            fi
            rm build.tar.gz